/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package npc.register;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.DriverManager;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ndach
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        log = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        uName = new javax.swing.JLabel();
        pWord = new javax.swing.JLabel();
        passWord = new javax.swing.JPasswordField();
        mophe = new javax.swing.JLabel();
        logIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BGKeyTyped(evt);
            }
        });
        BG.setLayout(null);

        log.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        log.setForeground(new java.awt.Color(0, 204, 51));
        log.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        log.setText("Log In");
        BG.add(log);
        log.setBounds(60, 0, 170, 40);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/npc/register/npc.png"))); // NOI18N
        BG.add(logo);
        logo.setBounds(30, 40, 230, 200);

        userName.setBackground(new java.awt.Color(255, 255, 255));
        userName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userName.setForeground(new java.awt.Color(0, 0, 0));
        userName.setBorder(new javax.swing.border.LineBorder(java.awt.Color.green, 2, true));
        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameKeyTyped(evt);
            }
        });
        BG.add(userName);
        userName.setBounds(10, 270, 280, 40);

        uName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        uName.setForeground(new java.awt.Color(0, 0, 0));
        uName.setText("User Name");
        BG.add(uName);
        uName.setBounds(10, 240, 100, 20);

        pWord.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        pWord.setForeground(new java.awt.Color(0, 0, 0));
        pWord.setText("Password");
        BG.add(pWord);
        pWord.setBounds(10, 320, 100, 20);

        passWord.setBackground(new java.awt.Color(255, 255, 255));
        passWord.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passWord.setForeground(new java.awt.Color(0, 0, 0));
        passWord.setBorder(new javax.swing.border.LineBorder(java.awt.Color.green, 2, true));
        passWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passWordKeyTyped(evt);
            }
        });
        BG.add(passWord);
        passWord.setBounds(10, 350, 280, 40);

        mophe.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        mophe.setForeground(new java.awt.Color(204, 204, 204));
        mophe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mophe.setText("Morpheus Softwares");
        BG.add(mophe);
        mophe.setBounds(0, 430, 130, 16);

        logIn.setBackground(new java.awt.Color(255, 255, 255));
        logIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logIn.setForeground(new java.awt.Color(0, 0, 0));
        logIn.setText("Log In");
        logIn.setBorder(new javax.swing.border.LineBorder(java.awt.Color.green, 2, true));
        logIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logIn.setOpaque(false);
        logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logInMouseExited(evt);
            }
        });
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        BG.add(logIn);
        logIn.setBounds(200, 400, 90, 40);

        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseEntered
        logIn.setForeground(Color.green);
    }//GEN-LAST:event_logInMouseEntered

    private void logInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseExited
        logIn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_logInMouseExited

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        login(userName, passWord);
    }//GEN-LAST:event_logInActionPerformed

    private void userNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login(userName, passWord);
        }
    }//GEN-LAST:event_userNameKeyTyped

    private void passWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login(userName, passWord);
        }
    }//GEN-LAST:event_passWordKeyTyped

    private void BGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BGKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login(userName, passWord);
        }
    }//GEN-LAST:event_BGKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel log;
    private javax.swing.JButton logIn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mophe;
    private javax.swing.JLabel pWord;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JLabel uName;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    private static Connection myConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost"
                    + ":3306/npc_register", "root", "001008186116002");
            return connection;
        } catch (ClassNotFoundException | SQLException ex) {
        }
        return null;
    }

    private void login(JTextField textField, JPasswordField passwordField) {
        String username = textField.getText();
        String password = String.valueOf(passwordField.getPassword());

        try {
            String sql = "SELECT * FROM `login` WHERE username = ?";
            PreparedStatement preparedStatement = (PreparedStatement) myConnection().prepareStatement(sql);
            preparedStatement.setString(1, textField.getText());
            ResultSet resultSet = (ResultSet) preparedStatement.executeQuery();

            if (resultSet.next()) {
                String uN = resultSet.getString("username");
                String pW = resultSet.getString("password");
                String dept = resultSet.getString("department");
                exportLog(dept);

                if (uN.equals(username) && pW.equals(password)) {
                    this.dispose();
                    new Register().setVisible(true);
                }
            } else if ("".equals(username) && "".equals(password)) {
                JOptionPane.showMessageDialog(this, "Username and Password are empty, type in Username and Password to Log In, please...", "Error", 1);
            } else if ("".equals(username)) {
                JOptionPane.showMessageDialog(this, "Username is empty, type in Username to Log In, please...", "Error", 1);
            } else if ("".equals(password)) {
                JOptionPane.showMessageDialog(this, "Password is empty, type in Password to Log In, please...", "Error", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", 1);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, "Error", 1);
        }
    }

    private void exportLog(String department) {
        try {
            FileOutputStream fos = new FileOutputStream("_.txt");
            try ( PrintWriter pw = new PrintWriter(fos)) {
                pw.write(department);
                pw.close();
                fos.close();
            } catch (IOException ex) {
            }
        } catch (FileNotFoundException fnfe) {
        }
    }

//    private void myMongoDBConnection() {
//        ConnectionString connectionString = new ConnectionString("mongodb+srv://ghost:<001008186116002>@npc-register.pvzcxcm.mongodb.net/?retryWrites=true&w=majority");
//        MongoClientSettings settings = MongoClientSettings.builder()
//                .applyConnectionString(connectionString)
//                .build();
//        MongoClient mongoClient = (MongoClient) MongoClients.create(settings);
//        MongoDatabase database = mongoClient.getDatabase("test");
//    }
}
